/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tiketbioskop;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author ATI-Dhio
 */
public class BuyTicketViewController extends javax.swing.JFrame {

    private ResultSet res;
    private Statement stat;

    DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
    Date date = new Date();

    String id_jadwal, id_transaksi;

    /**
     * Creates new form BuyTicketViewController
     *
     * @throws java.sql.SQLException
     */
    public BuyTicketViewController() throws SQLException {
        initComponents();
        this.setTitle("xixixi Bioskop");
        this.setLocationRelativeTo(null);
        KoneksiViewController connection = new KoneksiViewController();
        connection.getKoneksi();
        stat = connection.getKoneksi().createStatement();

        tampil_film();
    }

    private void tampil_film() throws SQLException {
        try {
            res = stat.executeQuery("select distinct judul_film from tb_film f, tb_jadwal j where f.id_film = j.id_film and f.visible = 'YA'");
            while (res.next()) {
                JudulFilm.addItem(res.getString("judul_film"));
            }
        } catch (Exception e) {

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        JudulFilm = new javax.swing.JComboBox<>();
        NamaStudio = new javax.swing.JTextField();
        JamTayang = new javax.swing.JComboBox<>();
        TotalBayar = new javax.swing.JTextField();
        JumlahTiket = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        TanggalTayang = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Judul Film");

        jLabel3.setText("Studio");

        jLabel4.setText("Jam Tayang");

        jLabel5.setText("Jumlah Tiket");

        jLabel6.setText("Total Bayar");

        JudulFilm.setMaximumRowCount(99);
        JudulFilm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Pilih Film -" }));
        JudulFilm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JudulFilmActionPerformed(evt);
            }
        });

        NamaStudio.setEditable(false);

        JamTayang.setMaximumRowCount(99);
        JamTayang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Pilih Jam -" }));
        JamTayang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JamTayangActionPerformed(evt);
            }
        });

        TotalBayar.setEditable(false);

        JumlahTiket.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36" }));
        JumlahTiket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JumlahTiketActionPerformed(evt);
            }
        });

        jButton1.setText("Booking");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel7.setText("Tanggal");

        jLabel1.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Pemesanan Tiket");
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        TanggalTayang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Pilih Tanggal -" }));
        TanggalTayang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TanggalTayangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1)
                            .addComponent(JamTayang, 0, 280, Short.MAX_VALUE)
                            .addComponent(JudulFilm, 0, 280, Short.MAX_VALUE)
                            .addComponent(NamaStudio, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JumlahTiket, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TotalBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TanggalTayang, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(JudulFilm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(TanggalTayang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(JamTayang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(NamaStudio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(JumlahTiket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(TotalBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void JudulFilmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JudulFilmActionPerformed
        // TODO add your handling code here:
        String judul_film = JudulFilm.getSelectedItem().toString();
        
                // Clear All first
        if (TanggalTayang.getItemCount() > 1) {
            for (int i = TanggalTayang.getItemCount() - 1; i > 0; i--) {
                TanggalTayang.removeItemAt(i);
            }
        }
        
        try {
            res = stat.executeQuery("SELECT DISTINCT date FROM tb_film f, tb_jadwal j WHERE f.id_film = j.id_film and f.visible = 'YA' and f.judul_film = '" + judul_film + "' ORDER BY 1 ASC");
            while (res.next()) {
                TanggalTayang.addItem(res.getString("date"));
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_JudulFilmActionPerformed

    private void JamTayangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JamTayangActionPerformed
        // TODO add your handling code here:

        String judul_film = JudulFilm.getSelectedItem().toString();
        String jam = JamTayang.getSelectedItem().toString();

        try {
            res = stat.executeQuery("select nama_studio from tb_film f, tb_jadwal j, tb_studio s where s.id_studio = j.id_studio and f.id_film = j.id_film and f.judul_film = '" + judul_film + "' and f.visible = 'YA' and jam = '" + jam + "'");
            while (res.next()) {
                NamaStudio.setText(res.getString("nama_studio"));
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_JamTayangActionPerformed

    private void JumlahTiketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JumlahTiketActionPerformed
        // TODO add your handling code here:
        String judul_film = JudulFilm.getSelectedItem().toString();
        String jam = JamTayang.getSelectedItem().toString();
        Integer jumlah = Integer.valueOf((String) JumlahTiket.getSelectedItem());

        try {
            res = stat.executeQuery("select id_jadwal, harga from tb_film f, tb_jadwal j where f.id_film = j.id_film and f.judul_film = '" + judul_film + "' and f.visible = 'YA' and jam = '" + jam + "'");
            while (res.next()) {
                int harga = res.getInt("harga");
                int total = harga * jumlah;
                TotalBayar.setText(String.valueOf(total));
                id_jadwal = res.getString("id_jadwal");
            }
        } catch (SQLException ex) {
            System.out.println(ex);
        }


    }//GEN-LAST:event_JumlahTiketActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String judulFilm = JudulFilm.getSelectedItem().toString();
        String tanggalTayang = TanggalTayang.getSelectedItem().toString();
        String jamTayang = JamTayang.getSelectedItem().toString();
        String namaStudio = NamaStudio.getText();
        String jumlahTiket = JumlahTiket.getSelectedItem().toString();
        String totalBayar = TotalBayar.getText();

        try {
            // TODO add your handling code here:
            stat.executeUpdate("insert into tb_transaksi (id_jadwal, date, total_bayar) values ('" + id_jadwal + "','" + tanggalTayang + "','" + totalBayar + "')");
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(BuyTicketViewController.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {
            res = stat.executeQuery("SELECT MAX(id_transaksi) AS id FROM tb_transaksi");
            while (res.next()) {
                id_transaksi = res.getString("id");
            }
        } catch (SQLException ex) {
            Logger.getLogger(BuyTicketViewController.class.getName()).log(Level.SEVERE, null, ex);
        }

        // Passing value to SeatViewController
        try {
            SeatViewController seatVC = new SeatViewController();
            seatVC.judul_film.setText(String.valueOf(judulFilm));
            seatVC.nama_studio.setText(String.valueOf(namaStudio));
            seatVC.id_jadwal.setText(id_jadwal);
            seatVC.tanggal_tayang.setText(String.valueOf(tanggalTayang));
            seatVC.jam_tayang.setText(String.valueOf(jamTayang));
            seatVC.jumlah_tiket.setText(String.valueOf(jumlahTiket));
            seatVC.total_bayar.setText(String.valueOf(totalBayar));
            seatVC.id_transaksi.setText(String.valueOf(id_transaksi));
            seatVC.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(BuyTicketViewController.class.getName()).log(Level.SEVERE, null, ex);
        }

//        UploadViewController UploadVC = null;
//        try {
//            UploadVC = new UploadViewController();
//        } catch (SQLException ex) {
//            Logger.getLogger(BuyTicketViewController.class.getName()).log(Level.SEVERE, null, ex);
//        }
//        UploadViewController.idUpload.setText(this.id_transaksi);
//        UploadVC.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void TanggalTayangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TanggalTayangActionPerformed
        // TODO add your handling code here:
        String judul_film = JudulFilm.getSelectedItem().toString();
        String tanggal_tayang = TanggalTayang.getSelectedItem().toString();
        
        // Clear All first
        if (JamTayang.getItemCount() > 1) {
            for (int i = JamTayang.getItemCount() - 1; i > 0; i--) {
                JamTayang.removeItemAt(i);
            }
        }

        try {
            res = stat.executeQuery("SELECT DISTINCT jam FROM tb_film f, tb_jadwal j WHERE f.id_film = j.id_film and f.visible = 'YA' and f.judul_film = '" + judul_film + "' and j.date = '" + tanggal_tayang + "' ORDER BY 1 ASC");
            while (res.next()) {
                JamTayang.addItem(res.getString("jam"));
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_TanggalTayangActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuyTicketViewController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuyTicketViewController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuyTicketViewController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuyTicketViewController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new BuyTicketViewController().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(BuyTicketViewController.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> JamTayang;
    private javax.swing.JComboBox<String> JudulFilm;
    public javax.swing.JComboBox<String> JumlahTiket;
    private javax.swing.JTextField NamaStudio;
    private javax.swing.JComboBox<String> TanggalTayang;
    private javax.swing.JTextField TotalBayar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
